Refactor only run hook for merge commits

diff --git a/git-hooks/prepare-commit-msg b/git-hooks/prepare-commit-msg
--- a/git-hooks/prepare-commit-msg
+++ b/git-hooks/prepare-commit-msg
@@ -1,3 +1,20 @@
 #!/usr/bin/env bash
 
+# Skip hook on non-merge commits
+if [ "xmerge" != "x$2" ]; then
+    exit 0
+fi
+
 npm run lint && npm run test
+
+STATUS=$?
+
+if [ 0 -ne $STATUS ]; then
+    echo "Lint/tests exited with a non-zero status: $STATUS" >&2
+    echo "Fix errors and commit again" >&2
+    echo "This hook can be skipped using --no-verify" >&2
+
+    exit $STATUS
+fi
+
+exit 0
